### ISSUE TITLE
Chained Parameter in Search

### ISSUE THREAD

**Issue by sdhakal-xealth** [awsdocs/amazon-healthlake-dev-guide#1]
I am trying to perform [chained param search](https://www.hl7.org/fhir/search.html#chaining) and I cannot get it working with healthlake. Can you provide more example related to this ? 
For example:
I want Observation FHIR resource where patient.name=Christopher. 

It would be great if you guys added more documentation regarding [search with modifiers](https://www.hl7.org/fhir/search.html#modifiers) as well

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
